site_name: How to Deploy Django
repo_url: https://github.com/HanZawNyein/deploy-django-to-python-anywhere
theme:
  name: material
  font: 
    text: Roboto
  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.footer
    - content.code.copy
    - content.code.select
    - navigation.sections
    - navigation.path
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HanZawNyein
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hanzawnyeindev


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  
plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: HanZawNyein/deploy-django-to-python-anywhere
      branch: main
  - tags:
      tags_file: index.md
